### ISSUE TITLE
Elasticsearch Performance Changes

### ISSUE THREAD

**Issue by johnpyp** [johnpyp/rustlesearch#24]
1. Index By Year. We should be indexing by year to increase performance with explicit IDs. Performance  while using explicit ids decreases as index size increases. Multiple indexes could also improve read performance too, especially on large time ranges.

0 docs in index - 600k/min
200mil docs in index - 400k/min

2. Presorting. We should be using presorting so there is no sorting overhead (seems to be about 2.5x reduction when sorting overhead is removed). This will reduce indexing performance, though hopefully indexing by year will help to mitigate that.

3. Predefined mappings. By default, Elasticsearch will create unnecessary keyword mappings for all the fields, which can significantly reduce performance.

4. Use filter context instead of query context if possible. Gone over here: https://www.ebayinc.com/stories/blogs/tech/elasticsearch-performance-tuning-practice-at-ebay/

5. Reduce replica count & increase refresh interval. These are both index-time temporary changes. They'll reduce search performance while active, but should significantly increase index performance.

**Comment by johnpyp** [comment]
Mostly done, except for indexing by year.

**Comment by alg1142** [comment]
You should open a pr for the rest of these changes, and close it there

**Comment by johnpyp** [comment]
Now using unique ids with a better graceful exit instead of indexes by year/channel.
