### ISSUE TITLE
Dropdown for channels

### ISSUE THREAD

**Issue by johnpyp** [johnpyp/rustlesearch#25]
Use `/api/channels` route to get a list of channels and populate a channels dropdown rather than an input field.

**Comment by alg1142** [comment]
should still be an input field, but have suggestions as you type
hundreds of channels not very nice in a dropdowm

**Comment by johnpyp** [comment]
True, I'll make it an autocomplete tab
https://quasar.dev/vue-components/select#Filtering-and-autocomplete

**Comment by johnpyp** [comment]
Done.
