### ISSUE TITLE
Allow dates to be input as text

### ISSUE THREAD

**Issue by 161134050** [johnpyp/rustlesearch#57]
Currently, the dates are input via calendar picker, I would really like to just be able to type a date in

**Comment by johnpyp** [comment]
I've been feeling similarly, I think the date picker is just a bit of a nuisance compared to typing the date in, though it would need to be done in a nice way to integrate with the UI.

**Comment by 161134050** [comment]
> I've been feeling similarly, I think the date picker is just a bit of a nuisance compared to typing the date in, though it would need to be done in a nice way to integrate with the UI.

Can't you have a date-picker that also allows input as text?

**Comment by johnpyp** [comment]
Yes, probably. I kind of favor having no date picker UI at all, but I'm not sure what other people think about that.

**Comment by johnpyp** [comment]
Fixed in https://github.com/johnpyp/rustlesearch/commit/850c487f1e22993172734dbef31a0e06bcc75366
